- Jenkinsfile
> add credentials and login for artifactory

- tests/actions/TestContent.js
> run all tests

- package.json
Signed-off-by: Colin-Stone <30794003+Colin-Stone@users.noreply.github.com>
> Include API mediation version of editor

- WebContent/js/containers/NodeViewer.js
> On query change force a page reload

- WebContent/js/containers/JobNodeTree.js
- tests/components/JobNodeTree.js
> Import node type from constants and add tests for future

- WebContent/js/containers/NodeViewer.js
> Remove surrounding div from content viewer

- WebContent/js/actions/jobNodes.js
- WebContent/js/reducers/jobNodes.js
- tests/actions/TestJobNodes.js
> Filter by jobID in code as api does not support

- WebContent/js/components/JobFile.js
- WebContent/js/components/JobInstance.js
- WebContent/js/components/JobStep.js
- WebContent/js/containers/Filters.js
- WebContent/js/containers/JobTree.js
> Add HTML ID attributes for testing

- WebContent/css/styles.css
> Stop wrapping job to next line and instead scroll laterally

- Jenkinsfile
- package.json
- sonar-project.properties
> submit coverage report to sonarqube

- WebContent/js/actions/content.js
- WebContent/js/actions/filters.js
- WebContent/js/actions/jobNodes.js
- WebContent/js/actions/validation.js
- WebContent/js/components/JobInstance.js
- WebContent/js/reducers/jobNodes.js
- tests/actions/TestContent.js
- tests/actions/TestJobNodes.js
- tests/actions/TestValidation.js
- tests/reducers/TestJobNodes.js
- tests/testResources/actions/jobNodesResources.js
- tests/testResources/reducers/jobNodesResources.js
> Use new api endpoints from tomcat jobs explorer

- WebContent/js/actions/filters.js
- WebContent/js/actions/validation.js
- tests/actions/TestValidation.js
> switch to json response parsing and extract username from json

- package.json
> bump version to force build to pickup username bug fix

- WebContent/js/index.js
- package.json
> add route for /jobs so when filtering with wildcard the page will load

- WebContent/js/actions/jobNodes.js
- WebContent/js/containers/JobTree.js
- WebContent/js/reducers/filters.js
- WebContent/js/reducers/jobNodes.js
- package.json
- tests/testResources/reducers/filters.js
> When filter for job by id if no job found invalidate jobs and clear list

- WebContent/js/actions/content.js
- WebContent/js/reducers/jobNodes.js
- package.json
- tests/testResources/actions/content.js
- tests/testResources/actions/jobNodesResources.js
> Update job model names

- WebContent/js/containers/JobTree.js
> Add no jobs found message

- package.json
> use new ui server

- explorer-jes.ppf
Signed-off-by: Yan Li <raymondyanli@gmail.com>
> adding AppScan config file

- WebContent/js/components/Snackbar.js
- WebContent/js/containers/Filters.js
> Remove unsupported props

- package.json
> Only track unit test coverage of actions and reducers

- package.json
> Exclude comps from coverage

- WebContent/js/actions/content.js
- WebContent/js/components/JobInstance.js
- WebContent/js/containers/ContentViewer.js
- WebContent/js/reducers/content.js
- tests/actions/TestContent.js
- tests/reducers/TestContent.js
- tests/testResources/reducers/content.js
> Update editor content in store when switching between tabs

- WebContent/js/components/JobFile.js
> Add context menu and download option to job file

- WebContent/js/components/JobFile.js
- WebContent/js/containers/ContentViewer.js
> add class labels

- WebContent/js/actions/content.js
- WebContent/js/components/JobInstance.js
- tests/actions/TestContent.js
Relies on https://github.com/zowe/jobs/pull/75
> add option to view concatenated output files for a given job

- WebContent/js/actions/content.js
- WebContent/js/reducers/content.js
- tests/actions/TestContent.js
> Remove a content tab if the fetch fails

- README.md
> Provide better development getting started instructions

- WebContent/js/components/JobFile.js
> Add option to open output file in fullscreen/standalone

- scripts/explorer-jes-configure.sh
Signed-off-by: stevenhorsman <steven@uk.ibm.com>
For https://github.com/zowe/zowe-install-packaging/issues/754
> Create iframe in config

- package-lock.json
- package.json
> bump uglifyjs due to OWASP results

- package-lock.json
> refresh package-lock

- WebContent/js/components/JobFile.js
> Use window.location to create fullscreen link

- package-lock.json
- package.json
- tests/FVTTests/test/fileParameterView/testFileParameterView.js
- tests/FVTTests/test/filterParametersView/testFilterParameterView.js
- tests/FVTTests/test/homeView/testHomeView.js.js
> Use generalized check driver function

- WebContent/js/containers/Filters.js
- tests/FVTTests/test/homeView/testHomeView.js.js
> Re enable tests

- package.json
> bump to v1 for sso changes

- package.json
- scripts/explorer-jes-start.sh
> Add bpx jobname to start script

- Jenkinsfile
> Add default value to apiml debug profile

- Jenkinsfile
- package-lock.json
- package.json
> Newer fvt utils has fix for setting debug profiles when starting apiml

- scripts/delete-fvt-jobs.sh
> Prevent jq getting null value

- .github/pull_request_template.md
- CHANGLOG.md
- CONTRIBUTING.md
- README.md
> Add CONTRIBUTING.md CHANGELOG.md PR template and update readme

- WebContent/js/components/JobFile.js
- WebContent/js/components/JobInstance.js
- WebContent/js/components/RefreshIcon.js
- WebContent/js/components/dialogs/UpperCaseTextField.js
- WebContent/js/containers/ContentViewer.js
- WebContent/js/containers/Filters.js
- WebContent/js/containers/FullHeightTree.js
- WebContent/js/containers/JobTree.js
- WebContent/js/containers/pages/FullScreen.js
- WebContent/js/containers/pages/Jobs.js
- WebContent/js/index.js
- tests/FVTTests/homeView/testHomeView.ts
- tests/FVTTests/testFunctions.ts
> keyboard navs and aria roles 

- CHANGLOG.md
- WebContent/js/components/dialogs/LoginDialog.js
- WebContent/js/reducers/validation.js
- tests/UnitTests/reducers/TestValidation.js
- tests/UnitTests/testResources/reducers/validation.js
> Add a force login flag if a jobs request comes back as 401

- WebContent/js/index.js
- pluginDefinition.json
- webpack.config.js
> update plugin definition image src zlux, check true logger

- WebContent/js/components/JobFile.js
- WebContent/js/components/JobInstance.js
- WebContent/js/containers/pages/FullScreen.js
- WebContent/js/containers/pages/Jobs.js
- package-lock.json
- package.json
- [ X] Other (Please indicate)
- [X ] PR completes `npm run preCommit` without error
> Move back to divs and set z index of context menus

- WebContent/js/reducers/content.js
- tests/UnitTests/testResources/reducers/content.js
> Fix bug when switching tabs whilst content loading

- package.json
> update ui-server to serve compressed

- package.json
- scripts/explorer-jes-start.sh
This PR addresses Issue: 
https://github.com/zowe/explorer-ui-server/issues/35
- [X ] Bug fix
> rolled back ui server pre keyring

- CHANGELOG.md
- WebContent/js/actions/jobNodes.js
- WebContent/js/components/JobInstance.js
- WebContent/js/reducers/jobNodes.js
- tests/UnitTests/actions/TestJobNodes.js
- tests/UnitTests/reducers/TestJobNodes.js
- tests/UnitTests/testResources/actions/jobNodesResources.js
- tests/UnitTests/testResources/reducers/jobNodesResources.js
This PR addresses Issue: https://github.com/zowe/zlux/issues/274
> Support for multi select and multi purge

- .pax/pre-packaging.sh
This PR addresses Issue: Packaging size fix, removing dev dependency from install
- [ X] Bug fix
> removed dev dependencies when packaging ui server

- .pax/pre-packaging.sh
- .pax/prepare-workspace.sh
- CHANGELOG.md
- Jenkinsfile
- package-lock.json
- package.json
- scripts/prepare-fvt.sh
This PR addresses Issue: https://github.com/zowe/explorer-ui-server/issues/38
> fix packaging ui server tagging

- CHANGELOG.md
- scripts/explorer-jes-start.sh
This PR addresses Issue: https://github.com/zowe/explorer-ui-server/issues/44
> add default value  ZOWE_EXPLORER_FRAME_ANCESTORS

- scripts/explorer-jes-start.sh
Part of fixes to fulfill https://github.com/zowe/zowe-install-packaging/issues/1702.
Branch build has been embedded into a Zowe test build https://wash.zowe.org:8443/view/Zowe/job/zowe-install-packaging/job/users%252Fjack%252Fzwelnch/3/consoleFull and passed these tests:
- convenience build: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/job/users%252Fjack%252Fzwelnch/4/
- smpe ptf: https://wash.zowe.org:8443/view/Zowe/job/zowe-install-test/job/users%252Fjack%252Fzwelnch/5/
> trap int signal

- CHANGELOG.md
This PR addresses Issue: Changelog md changes for zowe v1.17
> material ui changelog update.

- .pax/pre-packaging.sh
- .pax/prepare-workspace.sh
> keep png in content folder

- .github/workflows/build_test.yml
Signed-off-by: Tom Zhang <14881754+FlappiTomic@users.noreply.github.com>
> Github actions Workflow Change

- package-lock.json
- package.json
Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>
> updating the node-fetch versions - fixing the vunerabilities

- tests/FVTTests/homeView/testHomeView.ts
Signed-off-by: Sergei Kurnevich <sergei.kurnevich@broadcom.com>
> Fix context menu items test

- .github/workflows/build_test.yml
- .github/workflows/code_scan.yml
- .gitignore
> Github Action implementation (new)

- .github/workflows/build_test.yml
- .github/workflows/code_scan.yml
Signed-off-by: Tom Zhang <14881754+FlappiTomic@users.noreply.github.com>
> Debug on syntax on prepare-fvt.sh arguments

- WebContent/js/actions/jobNodes.js
- WebContent/js/components/RefreshIcon.js
- WebContent/js/containers/Filters.js
- WebContent/js/containers/FullHeightTree.js
Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>
> fixing the lint error

- CHANGELOG.md
- WebContent/js/actions/jobNodes.js
- WebContent/js/components/RefreshIcon.js
- WebContent/js/containers/Filters.js
- WebContent/js/containers/FullHeightTree.js
- WebContent/zlux-hooks/register-handler.js
Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>
'*' support for JobId
UI
--->
> Small UI-resizing + add '*' support for jobId

- WebContent/js/actions/validation.js
- bin/delete-fvt-jobs.sh
- tests/FVTTests/testConfig.ts
- tests/UnitTests/actions/TestValidation.js
- tests/UnitTests/testResources/actions/validation.js
> Fix apiml urls

- CHANGELOG.md
- WebContent/js/containers/ContentViewer.js
Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>
> adding the different options to close the opened files (porting PR 305)
